news_sites:
  eluniversal:
    url: http://www.eluniversal.com.mx
    queries:
      homepage_article_links: '.field-content a'
      article_body: '.field.field-name-body.field-type-text-with-summary.field-label-hidden'
      article_title: '.pane-content h1'
  elpais:
    url: https://elpais.com
    queries:
      homepage_article_links: 'h2.articulo-titulo a'
      article_body: '.articulo-cuerpo p'
      article_title: '.articulo-titulares h1.articulo-titulo'
